title: Nguyen H. Phong # your name (or website title) here
logo: "/img/photo3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist and Computer Science Researcher. PhD's degree in July, 2023 from Coimbra University, Portugal -- one of the oldest universities in Europe (since 1290). Previously, MSc degree in
  Information Technology from Shinawatra University, Thailand and BSc in Physics from Vietnam Nationaly University, Hanoi.
  <br>
  <br>
  Skilled in Deep Learning (action recognition, image classification, image segmentation, etc.)
  <br>
  <br>
  <a href="https://www.cisuc.uc.pt/en/people/nguyen-phong">Member of Adaptive Computation at CISUC.</a>
  <br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
